add sending and getting data
htmlacademy-univer-javascript-1/2579773-kekstagram-5 pull request #10
Opened 2024-12-26 16:22 UTC by VlasovaNatalya

2024-12-28 15:55 UTC, dimohqa requested changes

2024-12-28 15:55 UTC, dimohqa commented on js/form.js
> +    if (pristine.validate()) {
Чтобы поддерживать более плоскую структуру в функциях чаще всего придерживаются такого формата:
```js
const func = () => {
  // Обрабатываем исключение. Чаще всего оно занимается меньше всего кода
  if (!success) {
     foo();
     
     return;
  }
  // продолжаем выполнение основного блока кода
  bar();
  ...
}
```

2024-12-28 15:55 UTC, dimohqa commented on js/form.js
> +      sendData(formData)
У тебя получился классный паттерн с передачей колбэков в функции `getData`. Почему решила отказаться от него при отправке данных?

2024-12-28 15:55 UTC, dimohqa commented on js/form.js
> +const sendPhoto = () => {
У тебя сейчас функция называется так будто она сразу отправляет данные на сервер. Особенно это видно в твоем модуле `main`:
```js
const loadPosts = getData((data) => {
  renderAllPosts(data);
}, console.error);

loadPosts();
sendPhoto();

addUploadListeners();
uploadPhoto();
```

Если бы я читал этот файл без знаний о проекте, то подумал, что ты:
1. Загружаешь посты
2. Отправляешь фотографии
3. Добавляешь обработчик для загрузки
4. Загружаешь фото

Но вроде бы все не совсем так... Давай подумаем над неймингом? Лучше пройтись по всему проекту, особенно в модуле `main`

2024-12-28 15:55 UTC, dimohqa commented on js/main.js
> +}, console.error);
Расскажи почему решила эту функцию расположить в основном модуле?

2024-12-28 15:55 UTC, dimohqa commented on js/form.js
>  import {isEscapeKey} from './util.js';
А чем модуль `util` отличается от модуля `functions`?

2024-12-30 09:22 UTC, VlasovaNatalya commented on js/form.js
>  import {isEscapeKey} from './util.js';
functions остался ещё от выполнения самого первого задания, забыла его удалить

2024-12-30 09:25 UTC, VlasovaNatalya commented on js/main.js
> +}, console.error);
на самом деле действовала по примеру в курсе, поэтому делала как было там
решила перенести её в другой модуль всё-таки

2024-12-30 09:25 UTC, VlasovaNatalya commented on js/form.js
> +const sendPhoto = () => {
да, поняла
попробовала поменять названия функциям, чтобы было понятнее, что они делают

2024-12-30 09:29 UTC, VlasovaNatalya commented on js/form.js
> +      sendData(formData)
поменяла функцию!
забыла доработать

2024-12-30 17:24 UTC, merged